trigger-world: THE_END
trigger-cause: VOID
blacklist:
  - ELYTRA
  - SHULKER_SHELL
  - ENDER_CHEST
  - OBSIDIAN
  - ENDER_PEARL
  - END_CRYSTAL
remove-non-curse-enchant: true
burst:
  radius: 2.0
  merge-similar: true
  pickup-delay-ticks: 10
