name: EndVoidRescue
version: ${project.version}
main: cn.endvoidrescue.EndVoidRescuePlugin
api-version: '${apiVersion}'
author: dayDReam
description: Protects ordinary items from void deaths in The End.
